// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Assets.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AssetMeasureInfo
    {
        /// <summary>
        /// Initializes a new instance of the AssetMeasureInfo class.
        /// </summary>
        public AssetMeasureInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssetMeasureInfo class.
        /// </summary>
        public AssetMeasureInfo(string id = default(string), string name = default(string), string type = default(string), int? minimum = default(int?), int? maximum = default(int?), string aggregation = default(string))
        {
            Id = id;
            Name = name;
            Type = type;
            Minimum = minimum;
            Maximum = maximum;
            Aggregation = aggregation;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Minimum")]
        public int? Minimum { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Maximum")]
        public int? Maximum { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Aggregation")]
        public string Aggregation { get; set; }

    }
}
