// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace Zuuse.Assets.Client.Models
{
    /// <summary> The AssetIdAndChildrenAssetReferences. </summary>
    public partial class AssetIdAndChildrenAssetReferences
    {
        /// <summary> Initializes a new instance of AssetIdAndChildrenAssetReferences. </summary>
        internal AssetIdAndChildrenAssetReferences()
        {
            Children = new ChangeTrackingList<AssetReference>();
        }

        /// <summary> Initializes a new instance of AssetIdAndChildrenAssetReferences. </summary>
        /// <param name="id"> . </param>
        /// <param name="children"> . </param>
        internal AssetIdAndChildrenAssetReferences(Guid? id, IReadOnlyList<AssetReference> children)
        {
            Id = id;
            Children = children;
        }

        public Guid? Id { get; }
        public IReadOnlyList<AssetReference> Children { get; }
    }
}
