// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Assets.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AssetAttributeInfo
    {
        /// <summary>
        /// Initializes a new instance of the AssetAttributeInfo class.
        /// </summary>
        public AssetAttributeInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssetAttributeInfo class.
        /// </summary>
        public AssetAttributeInfo(string id = default(string), string name = default(string), string validationRegex = default(string))
        {
            Id = id;
            Name = name;
            ValidationRegex = validationRegex;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ValidationRegex")]
        public string ValidationRegex { get; set; }

    }
}
