// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Zuuse.Assets.Client.Models
{
    /// <summary> The AssetAttributeInfo. </summary>
    public partial class AssetAttributeInfo
    {
        /// <summary> Initializes a new instance of AssetAttributeInfo. </summary>
        public AssetAttributeInfo()
        {
        }

        /// <summary> Initializes a new instance of AssetAttributeInfo. </summary>
        /// <param name="id"> . </param>
        /// <param name="name"> . </param>
        /// <param name="validationRegex"> . </param>
        internal AssetAttributeInfo(string id, string name, string validationRegex)
        {
            Id = id;
            Name = name;
            ValidationRegex = validationRegex;
        }

        public string Id { get; set; }
        public string Name { get; set; }
        public string ValidationRegex { get; set; }
    }
}
