// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Assets.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AssetTaxonomyInfo
    {
        /// <summary>
        /// Initializes a new instance of the AssetTaxonomyInfo class.
        /// </summary>
        public AssetTaxonomyInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssetTaxonomyInfo class.
        /// </summary>
        public AssetTaxonomyInfo(int? level = default(int?), string name = default(string))
        {
            Level = level;
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Level")]
        public int? Level { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

    }
}
