// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace Zuuse.Assets.Client.Models
{
    /// <summary> The Asset. </summary>
    public partial class Asset
    {
        /// <summary> Initializes a new instance of Asset. </summary>
        public Asset()
        {
            Children = new ChangeTrackingList<AssetReference>();
            GeometryReferences = new ChangeTrackingList<string>();
        }

        /// <summary> Initializes a new instance of Asset. </summary>
        /// <param name="id"> . </param>
        /// <param name="name"> . </param>
        /// <param name="locationParent"> . </param>
        /// <param name="functionParent"> . </param>
        /// <param name="children"> . </param>
        /// <param name="functionalLayer0"> . </param>
        /// <param name="functionalLayer1"> . </param>
        /// <param name="functionalLayer2"> . </param>
        /// <param name="functionalLayer3"> . </param>
        /// <param name="functionalLayer4"> . </param>
        /// <param name="functionalLayer5"> . </param>
        /// <param name="functionalLayer6"> . </param>
        /// <param name="functionalLayer7"> . </param>
        /// <param name="functionalLayer8"> . </param>
        /// <param name="functionalLayer9"> . </param>
        /// <param name="functionalId"> . </param>
        /// <param name="locationLayer0"> . </param>
        /// <param name="locationLayer1"> . </param>
        /// <param name="locationLayer2"> . </param>
        /// <param name="locationLayer3"> . </param>
        /// <param name="locationLayer4"> . </param>
        /// <param name="locationLayer5"> . </param>
        /// <param name="locationLayer6"> . </param>
        /// <param name="locationLayer7"> . </param>
        /// <param name="locationLayer8"> . </param>
        /// <param name="locationLayer9"> . </param>
        /// <param name="locationId"> . </param>
        /// <param name="attribute0"> . </param>
        /// <param name="attribute1"> . </param>
        /// <param name="attribute2"> . </param>
        /// <param name="attribute3"> . </param>
        /// <param name="attribute4"> . </param>
        /// <param name="attribute5"> . </param>
        /// <param name="attribute6"> . </param>
        /// <param name="attribute7"> . </param>
        /// <param name="attribute8"> . </param>
        /// <param name="attribute9"> . </param>
        /// <param name="measure0"> . </param>
        /// <param name="measure1"> . </param>
        /// <param name="measure2"> . </param>
        /// <param name="measure3"> . </param>
        /// <param name="measure4"> . </param>
        /// <param name="measure5"> . </param>
        /// <param name="measure6"> . </param>
        /// <param name="measure7"> . </param>
        /// <param name="measure8"> . </param>
        /// <param name="measure9"> . </param>
        /// <param name="isPhysical"> . </param>
        /// <param name="inheritedIsActive"> . </param>
        /// <param name="layerIndex"> . </param>
        /// <param name="projectId"> . </param>
        /// <param name="externalId"> . </param>
        /// <param name="modelHash"> . </param>
        /// <param name="keyWords"> . </param>
        /// <param name="latitude"> . </param>
        /// <param name="longitude"> . </param>
        /// <param name="isActive"> . </param>
        /// <param name="thumbnailRemoteFile"> . </param>
        /// <param name="previewRemoteFile"> . </param>
        /// <param name="summaryReference"> . </param>
        /// <param name="versionDate"> . </param>
        /// <param name="versionBy"> . </param>
        /// <param name="createdDate"> . </param>
        /// <param name="createdBy"> . </param>
        /// <param name="geometryReferences"> . </param>
        internal Asset(string id, string name, AssetReference locationParent, AssetReference functionParent, IList<AssetReference> children, string functionalLayer0, string functionalLayer1, string functionalLayer2, string functionalLayer3, string functionalLayer4, string functionalLayer5, string functionalLayer6, string functionalLayer7, string functionalLayer8, string functionalLayer9, string functionalId, string locationLayer0, string locationLayer1, string locationLayer2, string locationLayer3, string locationLayer4, string locationLayer5, string locationLayer6, string locationLayer7, string locationLayer8, string locationLayer9, string locationId, string attribute0, string attribute1, string attribute2, string attribute3, string attribute4, string attribute5, string attribute6, string attribute7, string attribute8, string attribute9, double? measure0, double? measure1, double? measure2, double? measure3, double? measure4, double? measure5, double? measure6, double? measure7, double? measure8, double? measure9, bool? isPhysical, bool? inheritedIsActive, int? layerIndex, string projectId, string externalId, string modelHash, string keyWords, double? latitude, double? longitude, bool? isActive, string thumbnailRemoteFile, string previewRemoteFile, string summaryReference, DateTimeOffset? versionDate, string versionBy, DateTimeOffset? createdDate, string createdBy, IList<string> geometryReferences)
        {
            Id = id;
            Name = name;
            LocationParent = locationParent;
            FunctionParent = functionParent;
            Children = children;
            FunctionalLayer0 = functionalLayer0;
            FunctionalLayer1 = functionalLayer1;
            FunctionalLayer2 = functionalLayer2;
            FunctionalLayer3 = functionalLayer3;
            FunctionalLayer4 = functionalLayer4;
            FunctionalLayer5 = functionalLayer5;
            FunctionalLayer6 = functionalLayer6;
            FunctionalLayer7 = functionalLayer7;
            FunctionalLayer8 = functionalLayer8;
            FunctionalLayer9 = functionalLayer9;
            FunctionalId = functionalId;
            LocationLayer0 = locationLayer0;
            LocationLayer1 = locationLayer1;
            LocationLayer2 = locationLayer2;
            LocationLayer3 = locationLayer3;
            LocationLayer4 = locationLayer4;
            LocationLayer5 = locationLayer5;
            LocationLayer6 = locationLayer6;
            LocationLayer7 = locationLayer7;
            LocationLayer8 = locationLayer8;
            LocationLayer9 = locationLayer9;
            LocationId = locationId;
            Attribute0 = attribute0;
            Attribute1 = attribute1;
            Attribute2 = attribute2;
            Attribute3 = attribute3;
            Attribute4 = attribute4;
            Attribute5 = attribute5;
            Attribute6 = attribute6;
            Attribute7 = attribute7;
            Attribute8 = attribute8;
            Attribute9 = attribute9;
            Measure0 = measure0;
            Measure1 = measure1;
            Measure2 = measure2;
            Measure3 = measure3;
            Measure4 = measure4;
            Measure5 = measure5;
            Measure6 = measure6;
            Measure7 = measure7;
            Measure8 = measure8;
            Measure9 = measure9;
            IsPhysical = isPhysical;
            InheritedIsActive = inheritedIsActive;
            LayerIndex = layerIndex;
            ProjectId = projectId;
            ExternalId = externalId;
            ModelHash = modelHash;
            KeyWords = keyWords;
            Latitude = latitude;
            Longitude = longitude;
            IsActive = isActive;
            ThumbnailRemoteFile = thumbnailRemoteFile;
            PreviewRemoteFile = previewRemoteFile;
            SummaryReference = summaryReference;
            VersionDate = versionDate;
            VersionBy = versionBy;
            CreatedDate = createdDate;
            CreatedBy = createdBy;
            GeometryReferences = geometryReferences;
        }

        public string Id { get; set; }
        public string Name { get; set; }
        public AssetReference LocationParent { get; set; }
        public AssetReference FunctionParent { get; set; }
        public IList<AssetReference> Children { get; }
        public string FunctionalLayer0 { get; set; }
        public string FunctionalLayer1 { get; set; }
        public string FunctionalLayer2 { get; set; }
        public string FunctionalLayer3 { get; set; }
        public string FunctionalLayer4 { get; set; }
        public string FunctionalLayer5 { get; set; }
        public string FunctionalLayer6 { get; set; }
        public string FunctionalLayer7 { get; set; }
        public string FunctionalLayer8 { get; set; }
        public string FunctionalLayer9 { get; set; }
        public string FunctionalId { get; set; }
        public string LocationLayer0 { get; set; }
        public string LocationLayer1 { get; set; }
        public string LocationLayer2 { get; set; }
        public string LocationLayer3 { get; set; }
        public string LocationLayer4 { get; set; }
        public string LocationLayer5 { get; set; }
        public string LocationLayer6 { get; set; }
        public string LocationLayer7 { get; set; }
        public string LocationLayer8 { get; set; }
        public string LocationLayer9 { get; set; }
        public string LocationId { get; set; }
        public string Attribute0 { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
        public string Attribute3 { get; set; }
        public string Attribute4 { get; set; }
        public string Attribute5 { get; set; }
        public string Attribute6 { get; set; }
        public string Attribute7 { get; set; }
        public string Attribute8 { get; set; }
        public string Attribute9 { get; set; }
        public double? Measure0 { get; set; }
        public double? Measure1 { get; set; }
        public double? Measure2 { get; set; }
        public double? Measure3 { get; set; }
        public double? Measure4 { get; set; }
        public double? Measure5 { get; set; }
        public double? Measure6 { get; set; }
        public double? Measure7 { get; set; }
        public double? Measure8 { get; set; }
        public double? Measure9 { get; set; }
        public bool? IsPhysical { get; set; }
        public bool? InheritedIsActive { get; set; }
        public int? LayerIndex { get; set; }
        public string ProjectId { get; set; }
        public string ExternalId { get; set; }
        public string ModelHash { get; set; }
        public string KeyWords { get; set; }
        public double? Latitude { get; set; }
        public double? Longitude { get; set; }
        public bool? IsActive { get; set; }
        public string ThumbnailRemoteFile { get; set; }
        public string PreviewRemoteFile { get; set; }
        public string SummaryReference { get; set; }
        public DateTimeOffset? VersionDate { get; set; }
        public string VersionBy { get; set; }
        public DateTimeOffset? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public IList<string> GeometryReferences { get; }
    }
}
