// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace Zuuse.Assets.Client.Models
{
    /// <summary> The AssetIdAndChildrenAssetLifecycleReferences. </summary>
    internal partial class AssetIdAndChildrenAssetLifecycleReferences
    {
        /// <summary> Initializes a new instance of AssetIdAndChildrenAssetLifecycleReferences. </summary>
        internal AssetIdAndChildrenAssetLifecycleReferences()
        {
            Children = new ChangeTrackingList<AssetLifecycleReference>();
        }

        public Guid? Id { get; }
        public IReadOnlyList<AssetLifecycleReference> Children { get; }
    }
}
