// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Zuuse.Assets.Client.Models
{
    /// <summary> The AssetLifecycleReference. </summary>
    public partial class AssetLifecycleReference
    {
        /// <summary> Initializes a new instance of AssetLifecycleReference. </summary>
        internal AssetLifecycleReference()
        {
        }

        /// <summary> Initializes a new instance of AssetLifecycleReference. </summary>
        /// <param name="id"> . </param>
        /// <param name="name"> . </param>
        /// <param name="isPhysical"> . </param>
        /// <param name="isActive"> . </param>
        /// <param name="lifecycleMethodId"> . </param>
        /// <param name="hasChildLifecycleMethods"> . </param>
        internal AssetLifecycleReference(string id, string name, bool? isPhysical, bool? isActive, int? lifecycleMethodId, bool? hasChildLifecycleMethods)
        {
            Id = id;
            Name = name;
            IsPhysical = isPhysical;
            IsActive = isActive;
            LifecycleMethodId = lifecycleMethodId;
            HasChildLifecycleMethods = hasChildLifecycleMethods;
        }

        public string Id { get; }
        public string Name { get; }
        public bool? IsPhysical { get; }
        public bool? IsActive { get; }
        public int? LifecycleMethodId { get; }
        public bool? HasChildLifecycleMethods { get; }
    }
}
