// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Zuuse.Assets.Client.Models
{
    /// <summary> The AssetTaxonomyInfo. </summary>
    public partial class AssetTaxonomyInfo
    {
        /// <summary> Initializes a new instance of AssetTaxonomyInfo. </summary>
        public AssetTaxonomyInfo()
        {
        }

        /// <summary> Initializes a new instance of AssetTaxonomyInfo. </summary>
        /// <param name="level"> . </param>
        /// <param name="name"> . </param>
        internal AssetTaxonomyInfo(int? level, string name)
        {
            Level = level;
            Name = name;
        }

        public int? Level { get; set; }
        public string Name { get; set; }
    }
}
