// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Assets.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class LifecycleSettingCountByMethod
    {
        /// <summary>
        /// Initializes a new instance of the LifecycleSettingCountByMethod
        /// class.
        /// </summary>
        public LifecycleSettingCountByMethod()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LifecycleSettingCountByMethod
        /// class.
        /// </summary>
        public LifecycleSettingCountByMethod(int? lifecycleMethodId = default(int?), int? settingCount = default(int?))
        {
            LifecycleMethodId = lifecycleMethodId;
            SettingCount = settingCount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LifecycleMethodId")]
        public int? LifecycleMethodId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SettingCount")]
        public int? SettingCount { get; set; }

    }
}
