// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Zuuse.Assets.Client.Models
{
    /// <summary> The PhysicalAssetCountForTaxonomy. </summary>
    public partial class PhysicalAssetCountForTaxonomy
    {
        /// <summary> Initializes a new instance of PhysicalAssetCountForTaxonomy. </summary>
        internal PhysicalAssetCountForTaxonomy()
        {
        }

        /// <summary> Initializes a new instance of PhysicalAssetCountForTaxonomy. </summary>
        /// <param name="id"> . </param>
        /// <param name="layer0"> . </param>
        /// <param name="layer1"> . </param>
        /// <param name="layer2"> . </param>
        /// <param name="layer3"> . </param>
        /// <param name="layer4"> . </param>
        /// <param name="layer5"> . </param>
        /// <param name="layer6"> . </param>
        /// <param name="layer7"> . </param>
        /// <param name="layer8"> . </param>
        /// <param name="layer9"> . </param>
        /// <param name="layerIndex"> . </param>
        /// <param name="assetCount"> . </param>
        internal PhysicalAssetCountForTaxonomy(string id, string layer0, string layer1, string layer2, string layer3, string layer4, string layer5, string layer6, string layer7, string layer8, string layer9, int? layerIndex, int? assetCount)
        {
            Id = id;
            Layer0 = layer0;
            Layer1 = layer1;
            Layer2 = layer2;
            Layer3 = layer3;
            Layer4 = layer4;
            Layer5 = layer5;
            Layer6 = layer6;
            Layer7 = layer7;
            Layer8 = layer8;
            Layer9 = layer9;
            LayerIndex = layerIndex;
            AssetCount = assetCount;
        }

        public string Id { get; }
        public string Layer0 { get; }
        public string Layer1 { get; }
        public string Layer2 { get; }
        public string Layer3 { get; }
        public string Layer4 { get; }
        public string Layer5 { get; }
        public string Layer6 { get; }
        public string Layer7 { get; }
        public string Layer8 { get; }
        public string Layer9 { get; }
        public int? LayerIndex { get; }
        public int? AssetCount { get; }
    }
}
