// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Assets.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PhysicalAssetCountForTaxonomy
    {
        /// <summary>
        /// Initializes a new instance of the PhysicalAssetCountForTaxonomy
        /// class.
        /// </summary>
        public PhysicalAssetCountForTaxonomy()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PhysicalAssetCountForTaxonomy
        /// class.
        /// </summary>
        public PhysicalAssetCountForTaxonomy(string id = default(string), string layer0 = default(string), string layer1 = default(string), string layer2 = default(string), string layer3 = default(string), string layer4 = default(string), string layer5 = default(string), string layer6 = default(string), string layer7 = default(string), string layer8 = default(string), string layer9 = default(string), int? layerIndex = default(int?), int? assetCount = default(int?))
        {
            Id = id;
            Layer0 = layer0;
            Layer1 = layer1;
            Layer2 = layer2;
            Layer3 = layer3;
            Layer4 = layer4;
            Layer5 = layer5;
            Layer6 = layer6;
            Layer7 = layer7;
            Layer8 = layer8;
            Layer9 = layer9;
            LayerIndex = layerIndex;
            AssetCount = assetCount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Layer0")]
        public string Layer0 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Layer1")]
        public string Layer1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Layer2")]
        public string Layer2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Layer3")]
        public string Layer3 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Layer4")]
        public string Layer4 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Layer5")]
        public string Layer5 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Layer6")]
        public string Layer6 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Layer7")]
        public string Layer7 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Layer8")]
        public string Layer8 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Layer9")]
        public string Layer9 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LayerIndex")]
        public int? LayerIndex { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetCount")]
        public int? AssetCount { get; set; }

    }
}
