// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace Zuuse.Assets.Client.Models
{
    /// <summary> The TaxonomyLevelDescriptor. </summary>
    public partial class TaxonomyLevelDescriptor
    {
        /// <summary> Initializes a new instance of TaxonomyLevelDescriptor. </summary>
        internal TaxonomyLevelDescriptor()
        {
            Children = new ChangeTrackingList<TaxonomyLevelDescriptor>();
        }

        /// <summary> Initializes a new instance of TaxonomyLevelDescriptor. </summary>
        /// <param name="name"> . </param>
        /// <param name="id"> . </param>
        /// <param name="isPhysical"> . </param>
        /// <param name="isActive"> . </param>
        /// <param name="children"> . </param>
        internal TaxonomyLevelDescriptor(string name, string id, bool? isPhysical, bool? isActive, IReadOnlyList<TaxonomyLevelDescriptor> children)
        {
            Name = name;
            Id = id;
            IsPhysical = isPhysical;
            IsActive = isActive;
            Children = children;
        }

        public string Name { get; }
        public string Id { get; }
        public bool? IsPhysical { get; }
        public bool? IsActive { get; }
        public IReadOnlyList<TaxonomyLevelDescriptor> Children { get; }
    }
}
